language: python
sudo: required
python:
  - 3.6

install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - unzip terraform.zip -d /tmp/terraform
  - sudo ln -s /tmp/terraform/terraform /usr/bin/terraform
  - pip install -r deployment/picinsight-lambda/requirements.txt -t deployment/picinsight-lambda/
  - pip install -r deployment/picinsight-lambda/requirements-test.txt

script:
  - cd deployment/terraform/
  - terraform init && terraform validate
  - cd ../picinsight-lambda
  - coverage run python tests.py

after_success:
  - codecov